FROM node:24-slim AS base

FROM base AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:auth

FROM base
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/cert ./cert
RUN npm ci --only=production
COPY --from=builder /usr/src/app/dist/apps/client-auth ./dist
ENTRYPOINT [ "node", "dist/main"]